package params

// nolint:gosec
const (
	PARAMS_GERRIT_BRANCH                  = "GERRIT_BRANCH"
	PARAMS_GERRIT_CHANGE_COMMIT_MESSAGE   = "GERRIT_CHANGE_COMMIT_MESSAGE"
	PARAMS_GERRIT_CHANGE_ID               = "GERRIT_CHANGE_ID"
	PARAMS_GERRIT_CHANGE_NUMBER           = "GERRIT_CHANGE_NUMBER"
	PARAMS_GERRIT_CHANGE_OWNER            = "GERRIT_CHANGE_OWNER"
	PARAMS_GERRIT_CHANGE_OWNER_EMAIL      = "GERRIT_CHANGE_OWNER_EMAIL"
	PARAMS_GERRIT_CHANGE_OWNER_NAME       = "GERRIT_CHANGE_OWNER_NAME"
	PARAMS_GERRIT_CHANGE_PRIVATE_STATE    = "GERRIT_CHANGE_PRIVATE_STATE"
	PARAMS_GERRIT_CHANGE_SUBJECT          = "GERRIT_CHANGE_SUBJECT"
	PARAMS_GERRIT_CHANGE_URL              = "GERRIT_CHANGE_URL"
	PARAMS_GERRIT_CHANGE_WIP_STATE        = "GERRIT_CHANGE_WIP_STATE"
	PARAMS_GERRIT_EVENT_TYPE              = "GERRIT_EVENT_TYPE"
	PARAMS_GERRIT_HOST                    = "GERRIT_HOST"
	PARAMS_GERRIT_NAME                    = "GERRIT_NAME"
	PARAMS_GERRIT_PATCHSET_NUMBER         = "GERRIT_PATCHSET_NUMBER"
	PARAMS_GERRIT_PATCHSET_REVISION       = "GERRIT_PATCHSET_REVISION"
	PARAMS_GERRIT_PATCHSET_UPLOADER       = "GERRIT_PATCHSET_UPLOADER"
	PARAMS_GERRIT_PATCHSET_UPLOADER_EMAIL = "GERRIT_PATCHSET_UPLOADER_EMAIL"
	PARAMS_GERRIT_PATCHSET_UPLOADER_NAME  = "GERRIT_PATCHSET_UPLOADER_NAME"
	PARAMS_GERRIT_PORT                    = "GERRIT_PORT"
	PARAMS_GERRIT_PROJECT                 = "GERRIT_PROJECT"
	PARAMS_GERRIT_REFSPEC                 = "GERRIT_REFSPEC"
	PARAMS_GERRIT_SCHEME                  = "GERRIT_SCHEME"
	PARAMS_GERRIT_TOPIC                   = "GERRIT_TOPIC"
)
