---
name: "ci"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check go.mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  tests-on-unix:
    needs: golangci-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.18
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.golang }}-
      - name: Run tests
        run: make test
        continue-on-error: false
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
